"""initial_schema

Revision ID: cdb4590661ad
Revises: 
Create Date: 2026-05-29 15:57:55.295989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb4590661ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.Enum('smartclock', 'visiondrive', name='device_type_enum'), nullable=False),
    sa.Column('device_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_table('game_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_device_score', 'game_scores', ['device_id', 'score'], unique=False)
    op.create_index(op.f('ix_game_scores_device_id'), 'game_scores', ['device_id'], unique=False)
    op.create_table('pomodoro_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('study', 'break', name='pomodoro_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pomodoro_device_timestamp', 'pomodoro_sessions', ['device_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_pomodoro_sessions_device_id'), 'pomodoro_sessions', ['device_id'], unique=False)
    op.create_table('seminar_recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='seminar_status_enum'), nullable=False),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('speed_score', sa.Float(), nullable=True),
    sa.Column('noise_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seminar_device_created', 'seminar_recordings', ['device_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_seminar_recordings_device_id'), 'seminar_recordings', ['device_id'], unique=False)
    op.create_table('sleep_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('alarm_enabled', sa.Boolean(), nullable=False),
    sa.Column('alarm_time', sa.String(length=5), nullable=True),
    sa.Column('sleep_duration', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('sleep_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', name='sleep_status_enum'), nullable=False),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sleep_device_start', 'sleep_sessions', ['device_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_sleep_sessions_device_id'), 'sleep_sessions', ['device_id'], unique=False)
    op.create_table('timer_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('study_duration', sa.Integer(), nullable=False),
    sa.Column('break_duration', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', name='trip_status_enum'), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_device_start', 'trips', ['device_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_trips_device_id'), 'trips', ['device_id'], unique=False)
    op.create_table('distraction_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.Enum('drowsiness', 'gaze_distraction', 'phone_use', name='distraction_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='distraction_severity_enum'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distraction_events_trip_id'), 'distraction_events', ['trip_id'], unique=False)
    op.create_index('ix_distraction_trip_ts', 'distraction_events', ['trip_id', 'timestamp'], unique=False)
    op.create_table('sleep_sensor_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sleep_session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sound_level', sa.Float(), nullable=False),
    sa.Column('light_level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sleep_session_id'], ['sleep_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sleep_batch_session_ts', 'sleep_sensor_batches', ['sleep_session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sleep_sensor_batches_sleep_session_id'), 'sleep_sensor_batches', ['sleep_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_sensor_batches_sleep_session_id'), table_name='sleep_sensor_batches')
    op.drop_index('ix_sleep_batch_session_ts', table_name='sleep_sensor_batches')
    op.drop_table('sleep_sensor_batches')
    op.drop_index('ix_distraction_trip_ts', table_name='distraction_events')
    op.drop_index(op.f('ix_distraction_events_trip_id'), table_name='distraction_events')
    op.drop_table('distraction_events')
    op.drop_index(op.f('ix_trips_device_id'), table_name='trips')
    op.drop_index('ix_trip_device_start', table_name='trips')
    op.drop_table('trips')
    op.drop_table('timer_configs')
    op.drop_index(op.f('ix_sleep_sessions_device_id'), table_name='sleep_sessions')
    op.drop_index('ix_sleep_device_start', table_name='sleep_sessions')
    op.drop_table('sleep_sessions')
    op.drop_table('sleep_configs')
    op.drop_index(op.f('ix_seminar_recordings_device_id'), table_name='seminar_recordings')
    op.drop_index('ix_seminar_device_created', table_name='seminar_recordings')
    op.drop_table('seminar_recordings')
    op.drop_index(op.f('ix_pomodoro_sessions_device_id'), table_name='pomodoro_sessions')
    op.drop_index('ix_pomodoro_device_timestamp', table_name='pomodoro_sessions')
    op.drop_table('pomodoro_sessions')
    op.drop_index(op.f('ix_game_scores_device_id'), table_name='game_scores')
    op.drop_index('ix_game_device_score', table_name='game_scores')
    op.drop_table('game_scores')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
